print("Write how many cups of coffee you will need:")
cups = int(input())
print("For", cups, "cups of coffee you will need:")
print(cups * 200, "ml of water")
print(cups * 50, "ml of milk")
print(cups * 15, "g of coffee beans")